# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_in <- function(distribution, set_n, set_mean, set_sd) {
    .Call('_terminaldigits_dist_in', PACKAGE = 'terminaldigits', distribution, set_n, set_mean, set_sd)
}

data_in <- function(distribution, set_n, set_mean, set_sd, duplicates) {
    .Call('_terminaldigits_data_in', PACKAGE = 'terminaldigits', distribution, set_n, set_mean, set_sd, duplicates)
}

violation <- function(sample_0, duplicates, type) {
    .Call('_terminaldigits_violation', PACKAGE = 'terminaldigits', sample_0, duplicates, type)
}

average_fre <- function(x) {
    .Call('_terminaldigits_average_fre', PACKAGE = 'terminaldigits', x)
}

average_fre2 <- function(x, n) {
    .Call('_terminaldigits_average_fre2', PACKAGE = 'terminaldigits', x, n)
}

ft_stat <- function(new_n, vec_1_frac, vec_2_frac) {
    .Call('_terminaldigits_ft_stat', PACKAGE = 'terminaldigits', new_n, vec_1_frac, vec_2_frac)
}

rms_stat <- function(new_n, vec_1_frac, vec_2_frac) {
    .Call('_terminaldigits_rms_stat', PACKAGE = 'terminaldigits', new_n, vec_1_frac, vec_2_frac)
}

chisq_stat <- function(draws, vec_1_frac, vec_2_frac) {
    .Call('_terminaldigits_chisq_stat', PACKAGE = 'terminaldigits', draws, vec_1_frac, vec_2_frac)
}

g2_stat <- function(draws, vec_1_frac, vec_2_frac) {
    .Call('_terminaldigits_g2_stat', PACKAGE = 'terminaldigits', draws, vec_1_frac, vec_2_frac)
}

perm_basic <- function(distribution, duplicates, set_n, set_mean, set_sd, decimals, reps, times, tolerance) {
    .Call('_terminaldigits_perm_basic', PACKAGE = 'terminaldigits', distribution, duplicates, set_n, set_mean, set_sd, decimals, reps, times, tolerance)
}

terminal_independence <- function(x, decimals, reps, tolerance, type) {
    .Call('_terminaldigits_terminal_independence', PACKAGE = 'terminaldigits', x, decimals, reps, tolerance, type)
}

int_dec <- function(s, decimals) {
    .Call('_terminaldigits_int_dec', PACKAGE = 'terminaldigits', s, decimals)
}

full_vec <- function(int_1, dec_1) {
    .Call('_terminaldigits_full_vec', PACKAGE = 'terminaldigits', int_1, dec_1)
}

actual_frac <- function(int_full, dec, new_n) {
    .Call('_terminaldigits_actual_frac', PACKAGE = 'terminaldigits', int_full, dec, new_n)
}

tab_it <- function(x, bins, a, b) {
    .Call('_terminaldigits_tab_it', PACKAGE = 'terminaldigits', x, bins, a, b)
}

perm_vector <- function(v, r_sum, c_sum) {
    .Call('_terminaldigits_perm_vector', PACKAGE = 'terminaldigits', v, r_sum, c_sum)
}

expected_cells <- function(r_frac, c_frac) {
    .Call('_terminaldigits_expected_cells', PACKAGE = 'terminaldigits', r_frac, c_frac)
}

out_vector_cpp <- function(c_sums) {
    .Call('_terminaldigits_out_vector_cpp', PACKAGE = 'terminaldigits', c_sums)
}

RCONT <- function(n, r_sum, c_sum) {
    .Call('_terminaldigits_RCONT', PACKAGE = 'terminaldigits', n, r_sum, c_sum)
}

